version: '3.4'

services:
  medicion:
    image: ${DOCKER_REGISTRY-}medicion
    build:
      context: .
      dockerfile: Medicion/Dockerfile
    ports:
        - "8000:80"
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "kaiowas"
        ACCEPT_EULA: "Y"
    ports:
        - "1434:1433"